export const productData = [
  {
    id: 1,
    image: "assets/img/product/product_1.jpg",
    name: "Hạt mèo Catsrang",
    price: 92000,
    discounted: 59000,
    created: "2025-05-20",
    updated: "2025-05-22",
    slug: "hat-meo-catsrang",
    description: "Hạt mèo Catsrang phù hợp cho mọi lứa tuổi, giàu dinh dưỡng, hỗ trợ tiêu hóa.",
    minAgeMonth: 1,
    minWeight: 0.5
  },
  {
    id: 2,
    image: "assets/img/product/product_2.jpg",
    name: "Thức ăn Royal Canin",
    price: 292000,
    discounted: 239000,
    created: "2025-05-19",
    updated: "2025-05-21",
    slug: "thuc-an-royal-canin",
    description: "Thức ăn cao cấp Royal Canin dành cho mèo trưởng thành, tăng cường sức khỏe lông và da.",
    minAgeMonth: 12,
    minWeight: 2
  },
  {
    id: 3,
    image: "assets/img/product/product_3.jpg",
    name: "Cát vệ sinh thú cưng",
    price: 108000,
    discounted: 72000,
    created: "2025-05-18",
    updated: "2025-05-20",
    slug: "cat-ve-sinh-thu-cung",
    description: "Cát vệ sinh tự nhiên, khử mùi tốt, không gây bụi, an toàn cho thú cưng.",
    minAgeMonth: 0,
    minWeight: 0
  },
  {
    id: 4,
    image: "assets/img/product/product_4.jpg",
    name: "Pate mèo vị hải sản",
    price: 82000,
    discounted: 67000,
    created: "2025-05-17",
    updated: "2025-05-19",
    slug: "pate-meo-hai-san",
    description: "Pate mèo vị hải sản thơm ngon, dành cho mèo từ 6 tháng tuổi trở lên.",
    minAgeMonth: 6,
    minWeight: 1
  },
  {
    id: 5,
    image: "assets/img/product/product_5.jpg",
    name: "Bóng đồ chơi cho mèo",
    price: 30000,
    discounted: 25000,
    created: "2025-05-16",
    updated: "2025-05-18",
    slug: "bong-do-choi-meo",
    description: "Bóng đồ chơi nhỏ gọn, giúp mèo vận động và giải trí.",
    minAgeMonth: 2,
    minWeight: 0.5
  },
  {
    id: 6,
    image: "assets/img/product/product_6.jpg",
    name: "Dây dắt chó cao cấp",
    price: 55000,
    discounted: 45000,
    created: "2025-05-15",
    updated: "2025-05-17",
    slug: "day-dat-cho-cao-cap",
    description: "Dây dắt chó bền chắc, phù hợp cho chó từ 5kg trở lên.",
    minAgeMonth: 6,
    minWeight: 5
  },
  {
    id: 7,
    image: "assets/img/product/product_7.jpg",
    name: "Thức ăn chó Pedigree",
    price: 120000,
    discounted: 99000,
    created: "2025-05-14",
    updated: "2025-05-16",
    slug: "thuc-an-cho-pedigree",
    description: "Thức ăn khô Pedigree cho chó trưởng thành, hỗ trợ xương khớp.",
    minAgeMonth: 12,
    minWeight: 3
  },
  {
    id: 8,
    image: "assets/img/product/product_8.jpg",
    name: "Chuồng mèo gấp gọn",
    price: 250000,
    discounted: 199000,
    created: "2025-05-13",
    updated: "2025-05-15",
    slug: "chuong-meo-gap-gon",
    description: "Chuồng mèo tiện lợi, dễ gấp gọn, phù hợp cho mèo mọi lứa tuổi.",
    minAgeMonth: 0,
    minWeight: 0
  },
  {
    id: 9,
    image: "assets/img/product/product_9.jpg",
    name: "Sữa tắm chó mèo",
    price: 65000,
    discounted: 55000,
    created: "2025-05-12",
    updated: "2025-05-14",
    slug: "sua-tam-cho-meo",
    description: "Sữa tắm dịu nhẹ, làm sạch lông, an toàn cho chó mèo từ 2 tháng tuổi.",
    minAgeMonth: 2,
    minWeight: 0.5
  },
  {
    id: 10,
    image: "assets/img/product/product_10.jpg",
    name: "Khay vệ sinh cho mèo",
    price: 95000,
    discounted: 80000,
    created: "2025-05-11",
    updated: "2025-05-13",
    slug: "khay-ve-sinh-meo",
    description: "Khay vệ sinh rộng rãi, dễ làm sạch, phù hợp cho mèo mọi lứa tuổi.",
    minAgeMonth: 0,
    minWeight: 0
  },
  {
    id: 11,
    image: "assets/img/product/product_11.jpg",
    name: "Áo cho chó nhỏ",
    price: 45000,
    discounted: 39000,
    created: "2025-05-10",
    updated: "2025-05-12",
    slug: "ao-cho-nho",
    description: "Áo giữ ấm cho chó nhỏ, phù hợp với chó từ 1kg trở lên.",
    minAgeMonth: 3,
    minWeight: 1
  },
  {
    id: 12,
    image: "assets/img/product/product_12.jpg",
    name: "Cây cào móng cho mèo",
    price: 180000,
    discounted: 149000,
    created: "2025-05-09",
    updated: "2025-05-11",
    slug: "cay-cao-mong-meo",
    description: "Cây cào móng bền chắc, giúp mèo mài móng và thư giãn.",
    minAgeMonth: 3,
    minWeight: 1
  },
];
